
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/chroma/chroma
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command:
      - redis-server
      - "--save"
      - ""
      - "--appendonly"
      - "no"
    restart: unless-stopped
